bdpratico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('pessoas.urls')),
    path('pessoas/', include('pessoas.urls')),
    path('admin/', admin.site.urls),
]

pessoas/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index_alias'),
    path('home', views.home, name='home_alias'),
    path('pacientes', views.pacientes.as_view(), name='pacientes_alias'),
    path('procedimentos', views.procedimentos.as_view(), name='procedimentos_alias'),
    path('pessoa_create/', views.pessoa_create.as_view(), name='pessoa_create_alias'),
    path('pessoa_update/<int:pk>/', views.pessoa_update.as_view(), name='pessoa_update_alias'),
    path('pessoa_delete/<int:pk>/', views.pessoa_delete.as_view(), name='pessoa_delete_alias'),
    path('pessoa_download/', views.pessoa_download, name='pessoa_download_alias'),
    path('procedimento_update/<int:pk>/', views.procedimento_update.as_view(), name='procedimento_update_alias'),
    path('procedimento_delete/<int:pk>/', views.procedimento_delete.as_view(), name='procedimento_delete_alias'),
    path('procedimento_create/', views.procedimento_create.as_view(), name='procedimento_create_alias'),
    path('procedimento_download/', views.procedimento_download, name='procedimento_download_alias'),
]

pessoas/models.py
from django.db import models

class pessoa(models.Model):
    PACIENTE = 'PA'
    MEDICO = 'ME'
    FUNCIONARIO = 'FU'
    FUNCAO_ESCOLHA = [
        (PACIENTE, 'Paciente'),
        (MEDICO, 'Médico'),
        (FUNCIONARIO, 'Funcionário')
    ]
    nome = models.CharField(max_length=50, null=False, blank=False, verbose_name='Nome')
    email = models.CharField(max_length=50, null=False, blank=False, verbose_name='E-mail')
    celular = models.CharField(max_length=20, null=True, blank=True, verbose_name='Celular')
    funcao = models.CharField(max_length=2, choices=FUNCAO_ESCOLHA, default=PACIENTE, verbose_name='Função')
    nascimento = models.DateField(null=True, blank=True, default='1900-01-01', verbose_name='Data de Nascimento')
    ativo = models.BooleanField(default=True, verbose_name='Cadastro Ativo')

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ['nome', 'funcao',]

class procedimento(models.Model):
    CONSULTA = 'CO'
    RETORNO = 'RE'
    CHECKUP = 'CH'

    PROCEDIMENTO_ESCOLHA = [
        (CONSULTA, 'Consulta'),
        (RETORNO, 'Retorno'),
        (CHECKUP, 'Check-up Geral')
    ]
    procedimento = models.CharField(max_length=2, choices=PROCEDIMENTO_ESCOLHA, default=CONSULTA, verbose_name='Procedimento')
    data_execucao = models.DateField(null=True, blank=True, verbose_name='Data de Execução')
    paciente = models.ForeignKey(pessoa, null=True, on_delete=models.CASCADE, related_name='paciente', verbose_name='Paciente')
    medico = models.ForeignKey(pessoa, null=True, on_delete=models.CASCADE, related_name='medico', verbose_name='Médico')

    def __str__(self):
        return self.procedimento

    class Meta:
        ordering = ['procedimento', 'data_execucao',]

pessoas/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from django.views.generic import ListView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from django_filters.views import FilterView

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django_tables2 import SingleTableView
from django.contrib.auth.mixins import UserPassesTestMixin

def index(request):
    return HttpResponse('Pessoas')

class pessoa_create(CreateView):
    from .models import pessoa
    model = pessoa
    fields = ['nome', 'email', 'celular', 'funcao', 'nascimento', 'ativo']
    success_url = reverse_lazy('pacientes_alias')
    def test_func(self):
        return self.request.user.has_perm('pessoas.add_pessoa')

class procedimento_create(CreateView):
    from .models import procedimento
    model = procedimento
    fields = ['procedimento', 'data_execucao', 'paciente', 'medico']
    success_url = reverse_lazy('procedimentos_alias')
    def test_func(self):
        return self.request.user.has_perm('pessoas.add_pessoa')

class pessoa_update(UserPassesTestMixin, UpdateView):
    from .models import pessoa
    model = pessoa
    fields = ['nome', 'email', 'celular', 'funcao', 'nascimento', 'ativo']
    success_url = reverse_lazy('pacientes_alias')
    def test_func(self):
        return self.request.user.has_perm('pessoas.change_pessoa')

class procedimento_update(UserPassesTestMixin, UpdateView):
    from .models import procedimento
    model = procedimento
    fields = ['procedimento', 'data_execucao', 'paciente', 'medico']
    success_url = reverse_lazy('procedimentos_alias')
    def test_func(self):
        return self.request.user.has_perm('pessoas.change_procedimento')

class pessoa_delete(UserPassesTestMixin, DeleteView):
    from .models import pessoa
    model = pessoa
    fields = ['nome', 'email', 'celular', 'funcao', 'nascimento', 'ativo']
    template_name_suffix = '_delete'
    success_url = reverse_lazy('pacientes_alias')
    def test_func(self):
        return self.request.user.has_perm('pessoas.delete_pessoa')

class procedimento_delete(UserPassesTestMixin, DeleteView):
    from .models import procedimento
    model = procedimento
    fields = ['procedimento', 'data_execucao', 'paciente', 'medico']
    template_name_suffix = '_delete'
    success_url = reverse_lazy('procedimentos_alias')
    def test_func(self):
        return self.request.user.has_perm('pessoas.delete_procedimento')

@login_required(login_url='index_alias')
def home(request):
    from .models import pessoa
    dicionario = {}
    query_funcao = "select id, nome, funcao from pessoas_pessoa where nome = '%s';" % request.user.get_full_name()
    query = """
    select
        a.id
        ,procedimento
        ,data_execucao
        ,b.nome as nome_medico
        ,c.nome as nome_paciente
    from 
        pessoas_procedimento a
        left join pessoas_pessoa b on a.medico_id = b.id
        left join pessoas_pessoa c on a.paciente_id = c.id
    where 
        b.nome = '%s'
        or c.nome = '%s'
    order by data_execucao desc
    limit 1;
    """ % (request.user.get_full_name(), request.user.get_full_name())
    dicionario['funcao'] = pessoa.objects.raw(query_funcao)
    dicionario['informacoes'] = pessoa.objects.raw(query)
    return render(request, 'home.html', dicionario)

class pacientes(SingleTableView, FilterView):
    def dispatch(self, request, *args, **kwargs):
        if request.user.has_perm("pessoas.view_pessoa"):
            return super().dispatch(request, *args, **kwargs)
        else:
            return render(request, 'pacientes_restricted.html')
    from .models import pessoa
    from .tables import pessoa_table
    model = pessoa
    table_class = pessoa_table
    template_name_suffix = '_pacientes'
    table_pagination = {"per_page": 5}
    def get_queryset(self):
        from .models import pessoa
        user = self.request.user
        if user.is_staff:
            return pessoa.objects.all()
        else:
            return pessoa.objects.filter(funcao = 'PA')
    template_name = 'pessoas/pacientes.html'

class procedimentos(SingleTableView, FilterView):
    def dispatch(self, request, *args, **kwargs):
        if request.user.has_perm("pessoas.view_procedimento"):
            return super().dispatch(request, *args, **kwargs)
        else:
            return render(request, 'procedimentos_restricted.html')
    from .models import procedimento
    from .tables import procedimento_table
    model = procedimento
    table_class = procedimento_table
    template_name_suffix = '_procedimento'
    table_pagination = {"per_page": 5}
    def get_queryset(self):
        from .models import procedimento
        user = self.request.user
        if user.is_staff:
            query = """
            SELECT 
                a.id
            FROM 
                pessoas_procedimento a
                left join pessoas_pessoa b on b.id = a.paciente_id
                left join pessoas_pessoa c on c.id = a.medico_id
            """
            return procedimento.objects.raw(query)
        else:
            name = f"{user.first_name} {user.last_name}"
            query = """
            SELECT 
                a.id
            FROM 
                pessoas_procedimento a
                left join pessoas_pessoa b on b.id = a.paciente_id
                left join pessoas_pessoa c on c.id = a.medico_id
            WHERE
                b.nome = '%s'
                or c.nome = '%s'
            """ % (name, name)
            return procedimento.objects.raw(query)
    template_name = 'pessoas/procedimentos.html'

def pessoa_download(request):
    import pandas as pd
    from .models import pessoa
    eixo_y = []
    p = pessoa.objects.all()
    for _regs in p:
        eixo_x = []
        eixo_x.append(_regs.id)
        eixo_x.append(_regs.nome)
        eixo_x.append(_regs.email)
        eixo_x.append(_regs.celular)
        eixo_x.append(_regs.nascimento)
        eixo_x.append(_regs.funcao)
        eixo_x.append(_regs.ativo)
        eixo_y.append(eixo_x)
    _rotulos_colunas = []
    _rotulos_colunas.append("id")
    _rotulos_colunas.append("nome")
    _rotulos_colunas.append("email")
    _rotulos_colunas.append("celular")
    _rotulos_colunas.append("nascimento")
    _rotulos_colunas.append("funcao")
    _rotulos_colunas.append("ativo")
    df = pd.DataFrame(eixo_y, columns=_rotulos_colunas)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=pessoas.csv'
    df.to_csv(path_or_buf=response, index=False)
    return response

def procedimento_download(request):
    import pandas as pd
    from .models import procedimento
    eixo_y = []
    p = procedimento.objects.all()
    for _regs in p:
        eixo_x = []
        eixo_x.append(_regs.id)
        eixo_x.append(_regs.procedimento)
        eixo_x.append(_regs.data_execucao)
        eixo_x.append(_regs.paciente)
        eixo_x.append(_regs.medico)
        eixo_y.append(eixo_x)
    _rotulos_colunas = []
    _rotulos_colunas.append("id")
    _rotulos_colunas.append("procedimento")
    _rotulos_colunas.append("data_execucao")
    _rotulos_colunas.append("paciente")
    _rotulos_colunas.append("medico")
    df = pd.DataFrame(eixo_y, columns=_rotulos_colunas)
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=procedimentos.csv'
    df.to_csv(path_or_buf=response, index=False)
    return response

### Login
def index(request):
    usuario = request.POST.get('username')
    senha = request.POST.get('password')
    user = authenticate(username=usuario, password=senha)
    if (user is not None):
        login(request, user)
        request.session['username'] = usuario
        request.session['password'] = senha
        request.session['usernamefull'] = user.get_full_name()
        from django.shortcuts import redirect
        return redirect('home_alias')
    else:
        return render(request, 'index.html')

pessoas/templates/pessoas/pacientes.html
{% extends "base/base.html" %}
{% load render_table from django_tables2 %}
{% block title %}Pacientes{% endblock %}

<!-- head -->
{% block head %}
{% include "base/navbar.html" %}
{% endblock %}

<!-- body -->
{% block body %}
<center>
    <img src="../static/pessoas.jpg" class="img-fluid" alt="Teste" width="50%">
    <br>
    {% render_table table %}
    <br>
    {% if perms.pessoas.add_pessoa %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <a href="{% url 'pessoa_create_alias' %}">
                    <input type="button" class="btn btn-success" value="Incluir novas pessoas">
                </a>
            </div>
            <div class="col-sm">
                <a href="{% url 'pessoa_download_alias' %}">
                    <input type="button" class="btn btn-primary" value="Download todas pessoas">
                </a>
            </div>
        </div>
    </div>
    {% endif %}

</center>
{% endblock %}

<!-- footer -->
{% block footer %}
{% include "base/footer.html" %}
{% endblock %}

pessoas/templates/pessoas/pessoa_delete.html
{% extends "base/base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Excluir Pessoas{% endblock %}

<!-- head -->
{% block head %}
{% include "base/navbar.html" %}
{% endblock %}

<!-- body -->
{% block body %}
            <center>
            <h1>Apagar registro</h1>
            <img src="{% static 'pessoas.jpg' %}" class="img-fluid" alt="Teste" width="50%">
            <form method="POST">
                {% csrf_token %}
                <p>{{object.nome}}</p>
                <button type="submit" class="btn btn-danger">Sim, exclua!</button> &nbsp;
            </form>
            </center>
{% endblock %}

<!-- footer -->
{% block footer %}
{% include "base/footer.html" %}
{% endblock %}

pessoas/templates/pessoas/pessoa_form.html
{% extends "base/base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Formulário de Pessoas{% endblock %}

<!-- head -->
{% block head %}
{% include "base/navbar.html" %}
{% endblock %}

<!-- body -->
{% block body %}
<div class="container">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <center>
            <img src="{% static 'pessoas.jpg' %}" class="img-fluid" alt="Teste" width="50%">
            <h1>Formulário Novo Cadastro</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_field form.nome placeholder='' %}
                <div class="container">
                    <div class="row">
                        <div class="col-sm">
                            {% bootstrap_field form.email placeholder='' style='height:15px;' %}
                        </div>
                        <div class="col-sm">
                            {% bootstrap_field form.celular placeholder='' %}
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-sm">
                            {% bootstrap_field form.funcao placeholder='' %}
                        </div>
                        <div class="col-sm">
                            {% bootstrap_field form.nascimento placeholder='' %}
                        </div>
                        <div class="col-sm">
                            {% bootstrap_field form.ativo placeholder='' %}
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Salvar</button>
            </form>
        </center>
{% endblock %}

        <!-- footer -->
{% block footer %}
{% include "base/footer.html" %}
{% endblock %}

pessoas/templates/pessoas/procedimento_delete.html
{% extends "base/base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Excluir Procedimentos{% endblock %}

<!-- head -->
{% block head %}
{% include "base/navbar.html" %}
{% endblock %}

<!-- body -->
{% block body %}
            <center>
            <h1>Apagar registro</h1>
            <img src="{% static 'procedimentos.jpg' %}" class="img-fluid" alt="Teste" width="50%">
            <form method="POST">
                {% csrf_token %}
                {% if object.procedimento == 'RE' %}
                    <p>Retorno, {{ object.data_execucao|date:"d/m/Y" }}</p>
                {% elif object.procedimento == 'CO' %}
                    <p>Consulta, {{ object.data_execucao|date:"d/m/Y" }}</p>
                {% elif object.procedimento == 'CH' %}
                    <p>Check-up, {{ object.data_execucao|date:"d/m/Y" }}</p>
                {% else %}
                    <p>{{ object.procedimento }}</p>
                {% endif %}
                <button type="submit" class="btn btn-danger">Sim, exclua!</button> &nbsp;
            </form>
        </center>
{% endblock %}

<!-- footer -->
{% block footer %}
{% include "base/footer.html" %}
{% endblock %}

pessoas/templates/pessoas/procedimento_form.html
{% extends "base/base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap5 %}
{% load static %}
{% block title %}Formulário de Procedimentos{% endblock %}

<!-- head -->
{% block head %}
{% include "base/navbar.html" %}
{% endblock %}

<!-- body -->
{% block body %}
<center>
    <img src="{% static 'procedimentos.jpg' %}" class="img-fluid" alt="Teste" width="35%">
    <h1>Formulário Procedimento</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    {% bootstrap_field form.procedimento placeholder='' %}
                </div>
                <div class="col-sm">
                    {% bootstrap_field form.data_execucao placeholder='' style='height:15px;' %}
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    {% bootstrap_field form.paciente placeholder='' %}
                </div>
                <div class="col-sm">
                    {% bootstrap_field form.medico placeholder='' %}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
        </div>
    </form>
</center>
{% endblock %}

<!-- footer -->
{% block footer %}
{% include "base/footer.html" %}
{% endblock %}

pessoas/templates/pessoas/procedimentos.html
{% extends "base/base.html" %}
{% load render_table from django_tables2 %}
{% block title %}Procedimentos{% endblock %}

<!-- head -->
{% block head %}
{% include "base/navbar.html" %}
{% endblock %}

<!-- body -->
{% block body %}
<center>
    <img src="../static/procedimentos.jpg" class="img-fluid" alt="Teste" width="35%">
    <br>
    {% render_table table %}
    <br>
    {% if perms.pessoas.add_procedimento %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <a href="{% url 'procedimento_create_alias' %}">
                    <input type="button" class="btn btn-success" value="Incluir novos procedimentos">
                </a>
            </div>
            <div class="col-sm">
                <a href="{% url 'procedimento_download_alias' %}">
                    <input type="button" class="btn btn-primary" value="Download todos procedimentos">
                </a>
            </div>
        </div>
    </div>
    {% endif %}
    
</center>
{% endblock %}

<!-- footer -->
{% block footer %}
{% include "base/footer.html" %}
{% endblock %}